version: "3.8"

services:
  configserver:
    image: fernandofuentesfullstack/configserver:0.0.2-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      - fernandofuentesfullstack-network

  eurekaserver:
    image: fernandofuentesfullstack/eurekaserver:0.0.2-SNAPSHOT
    ports:
      - "8070:8070"
    networks:
      - fernandofuentesfullstack-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  accounts:
    image: fernandofuentesfullstack/accounts:0.0.2-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - fernandofuentesfullstack-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  loans:
    image: fernandofuentesfullstack/loans:0.0.2-SNAPSHOT
    ports:
      - "8090:8090"
    networks:
      - fernandofuentesfullstack-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  cards:
    image: fernandofuentesfullstack/cards:0.0.2-SNAPSHOT
    ports:
      - "9000:9000"
    networks:
      - fernandofuentesfullstack-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

networks:
  fernandofuentesfullstack-network: